package com.zhsj.m.dao;

import com.zhsj.m.model.AccountBindRole;

public interface AccountBindRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account_bind_role
     *
     * @mbggenerated Sun Oct 15 17:35:16 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account_bind_role
     *
     * @mbggenerated Sun Oct 15 17:35:16 CST 2017
     */
    int insert(AccountBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account_bind_role
     *
     * @mbggenerated Sun Oct 15 17:35:16 CST 2017
     */
    int insertSelective(AccountBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account_bind_role
     *
     * @mbggenerated Sun Oct 15 17:35:16 CST 2017
     */
    AccountBindRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account_bind_role
     *
     * @mbggenerated Sun Oct 15 17:35:16 CST 2017
     */
    int updateByPrimaryKeySelective(AccountBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account_bind_role
     *
     * @mbggenerated Sun Oct 15 17:35:16 CST 2017
     */
    int updateByPrimaryKey(AccountBindRole record);
}