package com.zhsj.m.dao;

import com.zhsj.m.model.Bank;

public interface BankDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_bank
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_bank
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    int insert(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_bank
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    int insertSelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_bank
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    Bank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_bank
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    int updateByPrimaryKeySelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_bank
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    int updateByPrimaryKey(Bank record);
}