package com.zhsj.m.dao;

import com.zhsj.m.model.CashSystemInfo;

public interface CashSystemInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cash_system
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cash_system
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    int insert(CashSystemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cash_system
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    int insertSelective(CashSystemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cash_system
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    CashSystemInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cash_system
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    int updateByPrimaryKeySelective(CashSystemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cash_system
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    int updateByPrimaryKey(CashSystemInfo record);
}