package com.zhsj.m.dao;

import com.zhsj.m.model.MchHourCount;

public interface MchHourCountDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mch_hour_count
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    int insert(MchHourCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mch_hour_count
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    int insertSelective(MchHourCount record);
}