package com.zhsj.m.dao;

import com.zhsj.m.model.MerchantInfo;

public interface MerchantInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    int insert(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    int insertSelective(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    MerchantInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    int updateByPrimaryKey(MerchantInfo record);
}