package com.zhsj.m.dao;

import com.zhsj.m.model.MerchantAccountBindShop;
import com.zhsj.m.util.db.DS;
import com.zhsj.m.util.db.DynamicDataSource;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@DynamicDataSource(DS.DB_MANAGER)
public interface MerchantAccountBindShopDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_shop
     *
     * @mbggenerated Mon Oct 23 23:19:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_shop
     *
     * @mbggenerated Mon Oct 23 23:19:09 CST 2017
     */
    int insert(MerchantAccountBindShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_shop
     *
     * @mbggenerated Mon Oct 23 23:19:09 CST 2017
     */
    int insertSelective(MerchantAccountBindShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_shop
     *
     * @mbggenerated Mon Oct 23 23:19:09 CST 2017
     */
    MerchantAccountBindShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_shop
     *
     * @mbggenerated Mon Oct 23 23:19:09 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantAccountBindShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_shop
     *
     * @mbggenerated Mon Oct 23 23:19:09 CST 2017
     */
    int updateByPrimaryKey(MerchantAccountBindShop record);
    /**
     *
     * @param accountId
     */
    void deleteWithAccountId(@Param("accountId") Integer accountId);

    List<MerchantAccountBindShop> getMerchantAccountBindShopListByAccountId(@Param("accountId") Integer accountId);

    List<MerchantAccountBindShop> getMerchantAccountBindShopListByShopName(@Param("shopName") String shopName);

}