package com.zhsj.m.dao;

import com.zhsj.m.model.MerchantActivityCode;
import com.zhsj.m.util.db.DS;
import com.zhsj.m.util.db.DynamicDataSource;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@DynamicDataSource(DS.DB_MANAGER)
public interface MerchantActivityCodeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int insert(MerchantActivityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int insertSelective(MerchantActivityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    MerchantActivityCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantActivityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int updateByPrimaryKey(MerchantActivityCode record);

    /**
     * 查询
     *
     * @param record
     * @return List<MerchantActivityCode>
     */
    public List<MerchantActivityCode> query(MerchantActivityCode record);

    /**
     * 查询
     *
     * @param record
     * @return List<MerchantActivityCode>
     */
    public Long queryCount(MerchantActivityCode record);
}