package com.zhsj.m.dao;

import com.zhsj.m.model.MerchantAccountBindRole;

public interface MerchantAccountBindRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_role
     *
     * @mbggenerated Tue Oct 17 14:40:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_role
     *
     * @mbggenerated Tue Oct 17 14:40:45 CST 2017
     */
    int insert(MerchantAccountBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_role
     *
     * @mbggenerated Tue Oct 17 14:40:45 CST 2017
     */
    int insertSelective(MerchantAccountBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_role
     *
     * @mbggenerated Tue Oct 17 14:40:45 CST 2017
     */
    MerchantAccountBindRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_role
     *
     * @mbggenerated Tue Oct 17 14:40:45 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantAccountBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_account_bind_role
     *
     * @mbggenerated Tue Oct 17 14:40:45 CST 2017
     */
    int updateByPrimaryKey(MerchantAccountBindRole record);
}