package com.zhsj.m.dao;

import com.zhsj.m.model.MerchantInfo;
import com.zhsj.m.model.RoleInfo;
import com.zhsj.m.util.db.DS;
import com.zhsj.m.util.db.DynamicDataSource;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@DynamicDataSource(DS.DB_MANAGER)
public interface MerchantInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 20:16:50 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 20:16:50 CST 2017
     */
    int insert(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 20:16:50 CST 2017
     */
    int insertSelective(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 20:16:50 CST 2017
     */
    MerchantInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 20:16:50 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant
     *
     * @mbggenerated Mon Oct 16 20:16:50 CST 2017
     */
    int updateByPrimaryKey(MerchantInfo record);

    List<MerchantInfo> getMerchantInfoList(MerchantInfo record);


    List<MerchantInfo> query(MerchantInfo merchantInfo);

    public Long queryCount(MerchantInfo merchantInfo);
}