package com.zhsj.m.dao;

import com.zhsj.m.model.MerchantActivityCodeInfo;

public interface MerchantActivityCodeInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int insert(MerchantActivityCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int insertSelective(MerchantActivityCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    MerchantActivityCodeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantActivityCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_merchant_activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    int updateByPrimaryKey(MerchantActivityCodeInfo record);
}