package com.zhsj.m.dao;

import com.zhsj.m.model.RoleBindRole;
import com.zhsj.m.util.db.DS;
import com.zhsj.m.util.db.DynamicDataSource;
import org.springframework.stereotype.Component;

@Component
@DynamicDataSource(DS.DB_MANAGER)
public interface RoleBindRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_bind_role
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_bind_role
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    int insert(RoleBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_bind_role
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    int insertSelective(RoleBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_bind_role
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    RoleBindRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_bind_role
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    int updateByPrimaryKeySelective(RoleBindRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_bind_role
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    int updateByPrimaryKey(RoleBindRole record);
}