package com.zhsj.m.dao;

import com.zhsj.m.model.TerminalDevice;
import com.zhsj.m.util.db.DS;
import com.zhsj.m.util.db.DynamicDataSource;
import org.springframework.stereotype.Component;

@Component
@DynamicDataSource(DS.DB_MANAGER)
public interface TerminalDeviceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_terminal_device
     *
     * @mbggenerated Thu Nov 02 22:26:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_terminal_device
     *
     * @mbggenerated Thu Nov 02 22:26:15 CST 2017
     */
    int insert(TerminalDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_terminal_device
     *
     * @mbggenerated Thu Nov 02 22:26:15 CST 2017
     */
    int insertSelective(TerminalDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_terminal_device
     *
     * @mbggenerated Thu Nov 02 22:26:15 CST 2017
     */
    TerminalDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_terminal_device
     *
     * @mbggenerated Thu Nov 02 22:26:15 CST 2017
     */
    int updateByPrimaryKeySelective(TerminalDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_terminal_device
     *
     * @mbggenerated Thu Nov 02 22:26:15 CST 2017
     */
    int updateByPrimaryKey(TerminalDevice record);
}