package com.zhsj.m.model;

public class AreaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.id
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.code
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.name
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.parent_id
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.level
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.order
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.name_en
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.shortname_en
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    private String shortnameEn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.id
     *
     * @return the value of tb_area.id
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.id
     *
     * @param id the value for tb_area.id
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.code
     *
     * @return the value of tb_area.code
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.code
     *
     * @param code the value for tb_area.code
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.name
     *
     * @return the value of tb_area.name
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.name
     *
     * @param name the value for tb_area.name
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.parent_id
     *
     * @return the value of tb_area.parent_id
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.parent_id
     *
     * @param parentId the value for tb_area.parent_id
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.level
     *
     * @return the value of tb_area.level
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.level
     *
     * @param level the value for tb_area.level
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.order
     *
     * @return the value of tb_area.order
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.order
     *
     * @param order the value for tb_area.order
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.name_en
     *
     * @return the value of tb_area.name_en
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.name_en
     *
     * @param nameEn the value for tb_area.name_en
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.shortname_en
     *
     * @return the value of tb_area.shortname_en
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public String getShortnameEn() {
        return shortnameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.shortname_en
     *
     * @param shortnameEn the value for tb_area.shortname_en
     *
     * @mbggenerated Tue Oct 17 18:49:22 CST 2017
     */
    public void setShortnameEn(String shortnameEn) {
        this.shortnameEn = shortnameEn == null ? null : shortnameEn.trim();
    }
}