package com.zhsj.m.model;

public class Bank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_bank.id
     *
     * @mbggenerated Sun Oct 29 09:44:28 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_bank.bank_name
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_bank.bank_code
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    private Integer bankCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_bank.id
     *
     * @return the value of td_bank.id
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_bank.id
     *
     * @param id the value for td_bank.id
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_bank.bank_name
     *
     * @return the value of td_bank.bank_name
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_bank.bank_name
     *
     * @param bankName the value for td_bank.bank_name
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_bank.bank_code
     *
     * @return the value of td_bank.bank_code
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    public Integer getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_bank.bank_code
     *
     * @param bankCode the value for td_bank.bank_code
     *
     * @mbggenerated Sun Oct 29 09:44:29 CST 2017
     */
    public void setBankCode(Integer bankCode) {
        this.bankCode = bankCode;
    }
}