package com.zhsj.m.model;

public class CashSystemInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.id
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.mch_code
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private String mchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.org_ids
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private String orgIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.type
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.case_name
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private String caseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.code
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.secretkey
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private String secretkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.position
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.is_used
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private Integer isUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.status
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.is_delete
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.utime
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private Integer utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cash_system.ctime
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    private Integer ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.id
     *
     * @return the value of tb_cash_system.id
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.id
     *
     * @param id the value for tb_cash_system.id
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.mch_code
     *
     * @return the value of tb_cash_system.mch_code
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public String getMchCode() {
        return mchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.mch_code
     *
     * @param mchCode the value for tb_cash_system.mch_code
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setMchCode(String mchCode) {
        this.mchCode = mchCode == null ? null : mchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.org_ids
     *
     * @return the value of tb_cash_system.org_ids
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public String getOrgIds() {
        return orgIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.org_ids
     *
     * @param orgIds the value for tb_cash_system.org_ids
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setOrgIds(String orgIds) {
        this.orgIds = orgIds == null ? null : orgIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.type
     *
     * @return the value of tb_cash_system.type
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.type
     *
     * @param type the value for tb_cash_system.type
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.case_name
     *
     * @return the value of tb_cash_system.case_name
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.case_name
     *
     * @param caseName the value for tb_cash_system.case_name
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.code
     *
     * @return the value of tb_cash_system.code
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.code
     *
     * @param code the value for tb_cash_system.code
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.secretkey
     *
     * @return the value of tb_cash_system.secretkey
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.secretkey
     *
     * @param secretkey the value for tb_cash_system.secretkey
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey == null ? null : secretkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.position
     *
     * @return the value of tb_cash_system.position
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.position
     *
     * @param position the value for tb_cash_system.position
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.is_used
     *
     * @return the value of tb_cash_system.is_used
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public Integer getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.is_used
     *
     * @param isUsed the value for tb_cash_system.is_used
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setIsUsed(Integer isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.status
     *
     * @return the value of tb_cash_system.status
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.status
     *
     * @param status the value for tb_cash_system.status
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.is_delete
     *
     * @return the value of tb_cash_system.is_delete
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.is_delete
     *
     * @param isDelete the value for tb_cash_system.is_delete
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.utime
     *
     * @return the value of tb_cash_system.utime
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.utime
     *
     * @param utime the value for tb_cash_system.utime
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cash_system.ctime
     *
     * @return the value of tb_cash_system.ctime
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cash_system.ctime
     *
     * @param ctime the value for tb_cash_system.ctime
     *
     * @mbggenerated Wed Oct 18 23:06:54 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }
}