package com.zhsj.m.model;

import java.util.Date;

public class ChannelInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.parent_id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.channel_name
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.channel_name2
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private String channelName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.system_id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Integer systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.channel_type
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Integer channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.url
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.status
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.display_order
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.description
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.create_time
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.update_time
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_channel_info.is_delete
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.id
     *
     * @return the value of tb_channel_info.id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.id
     *
     * @param id the value for tb_channel_info.id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.parent_id
     *
     * @return the value of tb_channel_info.parent_id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.parent_id
     *
     * @param parentId the value for tb_channel_info.parent_id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.channel_name
     *
     * @return the value of tb_channel_info.channel_name
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.channel_name
     *
     * @param channelName the value for tb_channel_info.channel_name
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.channel_name2
     *
     * @return the value of tb_channel_info.channel_name2
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public String getChannelName2() {
        return channelName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.channel_name2
     *
     * @param channelName2 the value for tb_channel_info.channel_name2
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setChannelName2(String channelName2) {
        this.channelName2 = channelName2 == null ? null : channelName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.system_id
     *
     * @return the value of tb_channel_info.system_id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.system_id
     *
     * @param systemId the value for tb_channel_info.system_id
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.channel_type
     *
     * @return the value of tb_channel_info.channel_type
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Integer getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.channel_type
     *
     * @param channelType the value for tb_channel_info.channel_type
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setChannelType(Integer channelType) {
        this.channelType = channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.url
     *
     * @return the value of tb_channel_info.url
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.url
     *
     * @param url the value for tb_channel_info.url
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.status
     *
     * @return the value of tb_channel_info.status
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.status
     *
     * @param status the value for tb_channel_info.status
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.display_order
     *
     * @return the value of tb_channel_info.display_order
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.display_order
     *
     * @param displayOrder the value for tb_channel_info.display_order
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.description
     *
     * @return the value of tb_channel_info.description
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.description
     *
     * @param description the value for tb_channel_info.description
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.create_time
     *
     * @return the value of tb_channel_info.create_time
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.create_time
     *
     * @param createTime the value for tb_channel_info.create_time
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.update_time
     *
     * @return the value of tb_channel_info.update_time
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.update_time
     *
     * @param updateTime the value for tb_channel_info.update_time
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_channel_info.is_delete
     *
     * @return the value of tb_channel_info.is_delete
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_channel_info.is_delete
     *
     * @param isDelete the value for tb_channel_info.is_delete
     *
     * @mbggenerated Tue Oct 17 16:59:59 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}