package com.zhsj.m.model;

import java.math.BigDecimal;

public class MchHourCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.pay_type
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.pay_method
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.rate
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.mch_code
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private String mchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.store_code
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private String storeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.org_id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.org_ids
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private String orgIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.consume_count
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer consumeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.consume_money
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private BigDecimal consumeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.refund_count
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer refundCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.stime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer stime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.service_charge
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private BigDecimal serviceCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.utime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.ctime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.sale_id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer saleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.shour
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private Integer shour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mch_hour_count.refund_money
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    private BigDecimal refundMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.id
     *
     * @return the value of tb_mch_hour_count.id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.id
     *
     * @param id the value for tb_mch_hour_count.id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.pay_type
     *
     * @return the value of tb_mch_hour_count.pay_type
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.pay_type
     *
     * @param payType the value for tb_mch_hour_count.pay_type
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.pay_method
     *
     * @return the value of tb_mch_hour_count.pay_method
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.pay_method
     *
     * @param payMethod the value for tb_mch_hour_count.pay_method
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setPayMethod(Integer payMethod) {
        this.payMethod = payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.rate
     *
     * @return the value of tb_mch_hour_count.rate
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.rate
     *
     * @param rate the value for tb_mch_hour_count.rate
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setRate(String rate) {
        this.rate = rate == null ? null : rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.mch_code
     *
     * @return the value of tb_mch_hour_count.mch_code
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public String getMchCode() {
        return mchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.mch_code
     *
     * @param mchCode the value for tb_mch_hour_count.mch_code
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setMchCode(String mchCode) {
        this.mchCode = mchCode == null ? null : mchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.store_code
     *
     * @return the value of tb_mch_hour_count.store_code
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.store_code
     *
     * @param storeCode the value for tb_mch_hour_count.store_code
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.org_id
     *
     * @return the value of tb_mch_hour_count.org_id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.org_id
     *
     * @param orgId the value for tb_mch_hour_count.org_id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.org_ids
     *
     * @return the value of tb_mch_hour_count.org_ids
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public String getOrgIds() {
        return orgIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.org_ids
     *
     * @param orgIds the value for tb_mch_hour_count.org_ids
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setOrgIds(String orgIds) {
        this.orgIds = orgIds == null ? null : orgIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.consume_count
     *
     * @return the value of tb_mch_hour_count.consume_count
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getConsumeCount() {
        return consumeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.consume_count
     *
     * @param consumeCount the value for tb_mch_hour_count.consume_count
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setConsumeCount(Integer consumeCount) {
        this.consumeCount = consumeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.consume_money
     *
     * @return the value of tb_mch_hour_count.consume_money
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public BigDecimal getConsumeMoney() {
        return consumeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.consume_money
     *
     * @param consumeMoney the value for tb_mch_hour_count.consume_money
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setConsumeMoney(BigDecimal consumeMoney) {
        this.consumeMoney = consumeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.refund_count
     *
     * @return the value of tb_mch_hour_count.refund_count
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getRefundCount() {
        return refundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.refund_count
     *
     * @param refundCount the value for tb_mch_hour_count.refund_count
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setRefundCount(Integer refundCount) {
        this.refundCount = refundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.stime
     *
     * @return the value of tb_mch_hour_count.stime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.stime
     *
     * @param stime the value for tb_mch_hour_count.stime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setStime(Integer stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.service_charge
     *
     * @return the value of tb_mch_hour_count.service_charge
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public BigDecimal getServiceCharge() {
        return serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.service_charge
     *
     * @param serviceCharge the value for tb_mch_hour_count.service_charge
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setServiceCharge(BigDecimal serviceCharge) {
        this.serviceCharge = serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.utime
     *
     * @return the value of tb_mch_hour_count.utime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.utime
     *
     * @param utime the value for tb_mch_hour_count.utime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.ctime
     *
     * @return the value of tb_mch_hour_count.ctime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.ctime
     *
     * @param ctime the value for tb_mch_hour_count.ctime
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.sale_id
     *
     * @return the value of tb_mch_hour_count.sale_id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.sale_id
     *
     * @param saleId the value for tb_mch_hour_count.sale_id
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.shour
     *
     * @return the value of tb_mch_hour_count.shour
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public Integer getShour() {
        return shour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.shour
     *
     * @param shour the value for tb_mch_hour_count.shour
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setShour(Integer shour) {
        this.shour = shour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mch_hour_count.refund_money
     *
     * @return the value of tb_mch_hour_count.refund_money
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public BigDecimal getRefundMoney() {
        return refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mch_hour_count.refund_money
     *
     * @param refundMoney the value for tb_mch_hour_count.refund_money
     *
     * @mbggenerated Sun Oct 29 21:13:15 CST 2017
     */
    public void setRefundMoney(BigDecimal refundMoney) {
        this.refundMoney = refundMoney;
    }
}