package com.zhsj.m.model;

public class MerchantAccount {

    private Integer id;


    private Integer foreignId;


    private String account;


    private String password;


    private String openId;


    private String name;


    private String headImg;


    private Integer gender;


    private String phone;


    private String eMail;


    private Integer accountType;


    private Integer status;


    private Integer isDelete;


    private Integer utime;


    private Integer ctime;


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.id
     *
     * @param id the value for tb_merchant_account.id
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.foreign_id
     *
     * @return the value of tb_merchant_account.foreign_id
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public Integer getForeignId() {
        return foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.foreign_id
     *
     * @param foreignId the value for tb_merchant_account.foreign_id
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setForeignId(Integer foreignId) {
        this.foreignId = foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.account
     *
     * @return the value of tb_merchant_account.account
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.account
     *
     * @param account the value for tb_merchant_account.account
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.password
     *
     * @return the value of tb_merchant_account.password
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.password
     *
     * @param password the value for tb_merchant_account.password
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.open_id
     *
     * @return the value of tb_merchant_account.open_id
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.open_id
     *
     * @param openId the value for tb_merchant_account.open_id
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.name
     *
     * @return the value of tb_merchant_account.name
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.name
     *
     * @param name the value for tb_merchant_account.name
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.head_img
     *
     * @return the value of tb_merchant_account.head_img
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.head_img
     *
     * @param headImg the value for tb_merchant_account.head_img
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.gender
     *
     * @return the value of tb_merchant_account.gender
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.gender
     *
     * @param gender the value for tb_merchant_account.gender
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.phone
     *
     * @return the value of tb_merchant_account.phone
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.phone
     *
     * @param phone the value for tb_merchant_account.phone
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.e_mail
     *
     * @return the value of tb_merchant_account.e_mail
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.e_mail
     *
     * @param eMail the value for tb_merchant_account.e_mail
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.account_type
     *
     * @return the value of tb_merchant_account.account_type
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.account_type
     *
     * @param accountType the value for tb_merchant_account.account_type
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.status
     *
     * @return the value of tb_merchant_account.status
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.status
     *
     * @param status the value for tb_merchant_account.status
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.is_delete
     *
     * @return the value of tb_merchant_account.is_delete
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.is_delete
     *
     * @param isDelete the value for tb_merchant_account.is_delete
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.utime
     *
     * @return the value of tb_merchant_account.utime
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.utime
     *
     * @param utime the value for tb_merchant_account.utime
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_account.ctime
     *
     * @return the value of tb_merchant_account.ctime
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_account.ctime
     *
     * @param ctime the value for tb_merchant_account.ctime
     *
     * @mbggenerated Tue Oct 17 14:40:44 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }
}