package com.zhsj.m.model;

public class MerchantActivityCodeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.id
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.activity_name
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private String activityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.mch_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private String mchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.org_ids
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private String orgIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.imei
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.status
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.is_delete
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.utime
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private Integer utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_activity_code.ctime
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    private Integer ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.id
     *
     * @return the value of tb_merchant_activity_code.id
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.id
     *
     * @param id the value for tb_merchant_activity_code.id
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.activity_name
     *
     * @return the value of tb_merchant_activity_code.activity_name
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.activity_name
     *
     * @param activityName the value for tb_merchant_activity_code.activity_name
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.activity_code
     *
     * @return the value of tb_merchant_activity_code.activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.activity_code
     *
     * @param activityCode the value for tb_merchant_activity_code.activity_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode == null ? null : activityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.mch_code
     *
     * @return the value of tb_merchant_activity_code.mch_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public String getMchCode() {
        return mchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.mch_code
     *
     * @param mchCode the value for tb_merchant_activity_code.mch_code
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setMchCode(String mchCode) {
        this.mchCode = mchCode == null ? null : mchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.org_ids
     *
     * @return the value of tb_merchant_activity_code.org_ids
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public String getOrgIds() {
        return orgIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.org_ids
     *
     * @param orgIds the value for tb_merchant_activity_code.org_ids
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setOrgIds(String orgIds) {
        this.orgIds = orgIds == null ? null : orgIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.imei
     *
     * @return the value of tb_merchant_activity_code.imei
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.imei
     *
     * @param imei the value for tb_merchant_activity_code.imei
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.status
     *
     * @return the value of tb_merchant_activity_code.status
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.status
     *
     * @param status the value for tb_merchant_activity_code.status
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.is_delete
     *
     * @return the value of tb_merchant_activity_code.is_delete
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.is_delete
     *
     * @param isDelete the value for tb_merchant_activity_code.is_delete
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.utime
     *
     * @return the value of tb_merchant_activity_code.utime
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.utime
     *
     * @param utime the value for tb_merchant_activity_code.utime
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_activity_code.ctime
     *
     * @return the value of tb_merchant_activity_code.ctime
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_activity_code.ctime
     *
     * @param ctime the value for tb_merchant_activity_code.ctime
     *
     * @mbggenerated Wed Oct 18 21:37:41 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }
}