package com.zhsj.m.model;



public class MerchantInfo extends BaseModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.id
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.mch_code
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String mchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.parent_code
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.org_id
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.org_ids
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String orgIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.type
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.short_name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.business_type
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.contact_phone
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.business_starttime_hour
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer businessStarttimeHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.business_starttime_min
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer businessStarttimeMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.business_endtime_hour
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer businessEndtimeHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.business_endtime_min
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer businessEndtimeMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.region
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.county
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.district
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.street
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.address
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.lon
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.lat
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.legal_person_name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String legalPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.legal_person_tel
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String legalPersonTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.email
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.has_settle
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer hasSettle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.status
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.is_delete
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.utime
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.ctime
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private Integer ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant.v_url
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    private String vUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.id
     *
     * @return the value of tb_merchant.id
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.id
     *
     * @param id the value for tb_merchant.id
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.mch_code
     *
     * @return the value of tb_merchant.mch_code
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getMchCode() {
        return mchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.mch_code
     *
     * @param mchCode the value for tb_merchant.mch_code
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setMchCode(String mchCode) {
        this.mchCode = mchCode == null ? null : mchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.parent_code
     *
     * @return the value of tb_merchant.parent_code
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.parent_code
     *
     * @param parentCode the value for tb_merchant.parent_code
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.org_id
     *
     * @return the value of tb_merchant.org_id
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.org_id
     *
     * @param orgId the value for tb_merchant.org_id
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.org_ids
     *
     * @return the value of tb_merchant.org_ids
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getOrgIds() {
        return orgIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.org_ids
     *
     * @param orgIds the value for tb_merchant.org_ids
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setOrgIds(String orgIds) {
        this.orgIds = orgIds == null ? null : orgIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.type
     *
     * @return the value of tb_merchant.type
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.type
     *
     * @param type the value for tb_merchant.type
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.short_name
     *
     * @return the value of tb_merchant.short_name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.short_name
     *
     * @param shortName the value for tb_merchant.short_name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.name
     *
     * @return the value of tb_merchant.name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.name
     *
     * @param name the value for tb_merchant.name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.business_type
     *
     * @return the value of tb_merchant.business_type
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.business_type
     *
     * @param businessType the value for tb_merchant.business_type
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.contact_phone
     *
     * @return the value of tb_merchant.contact_phone
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.contact_phone
     *
     * @param contactPhone the value for tb_merchant.contact_phone
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.business_starttime_hour
     *
     * @return the value of tb_merchant.business_starttime_hour
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getBusinessStarttimeHour() {
        return businessStarttimeHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.business_starttime_hour
     *
     * @param businessStarttimeHour the value for tb_merchant.business_starttime_hour
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setBusinessStarttimeHour(Integer businessStarttimeHour) {
        this.businessStarttimeHour = businessStarttimeHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.business_starttime_min
     *
     * @return the value of tb_merchant.business_starttime_min
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getBusinessStarttimeMin() {
        return businessStarttimeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.business_starttime_min
     *
     * @param businessStarttimeMin the value for tb_merchant.business_starttime_min
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setBusinessStarttimeMin(Integer businessStarttimeMin) {
        this.businessStarttimeMin = businessStarttimeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.business_endtime_hour
     *
     * @return the value of tb_merchant.business_endtime_hour
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getBusinessEndtimeHour() {
        return businessEndtimeHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.business_endtime_hour
     *
     * @param businessEndtimeHour the value for tb_merchant.business_endtime_hour
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setBusinessEndtimeHour(Integer businessEndtimeHour) {
        this.businessEndtimeHour = businessEndtimeHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.business_endtime_min
     *
     * @return the value of tb_merchant.business_endtime_min
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getBusinessEndtimeMin() {
        return businessEndtimeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.business_endtime_min
     *
     * @param businessEndtimeMin the value for tb_merchant.business_endtime_min
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setBusinessEndtimeMin(Integer businessEndtimeMin) {
        this.businessEndtimeMin = businessEndtimeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.region
     *
     * @return the value of tb_merchant.region
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.region
     *
     * @param region the value for tb_merchant.region
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.county
     *
     * @return the value of tb_merchant.county
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.county
     *
     * @param county the value for tb_merchant.county
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.district
     *
     * @return the value of tb_merchant.district
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.district
     *
     * @param district the value for tb_merchant.district
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.street
     *
     * @return the value of tb_merchant.street
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.street
     *
     * @param street the value for tb_merchant.street
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.address
     *
     * @return the value of tb_merchant.address
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.address
     *
     * @param address the value for tb_merchant.address
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.lon
     *
     * @return the value of tb_merchant.lon
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.lon
     *
     * @param lon the value for tb_merchant.lon
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.lat
     *
     * @return the value of tb_merchant.lat
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.lat
     *
     * @param lat the value for tb_merchant.lat
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.legal_person_name
     *
     * @return the value of tb_merchant.legal_person_name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getLegalPersonName() {
        return legalPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.legal_person_name
     *
     * @param legalPersonName the value for tb_merchant.legal_person_name
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setLegalPersonName(String legalPersonName) {
        this.legalPersonName = legalPersonName == null ? null : legalPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.legal_person_tel
     *
     * @return the value of tb_merchant.legal_person_tel
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getLegalPersonTel() {
        return legalPersonTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.legal_person_tel
     *
     * @param legalPersonTel the value for tb_merchant.legal_person_tel
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setLegalPersonTel(String legalPersonTel) {
        this.legalPersonTel = legalPersonTel == null ? null : legalPersonTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.email
     *
     * @return the value of tb_merchant.email
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.email
     *
     * @param email the value for tb_merchant.email
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.has_settle
     *
     * @return the value of tb_merchant.has_settle
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getHasSettle() {
        return hasSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.has_settle
     *
     * @param hasSettle the value for tb_merchant.has_settle
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setHasSettle(Integer hasSettle) {
        this.hasSettle = hasSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.status
     *
     * @return the value of tb_merchant.status
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.status
     *
     * @param status the value for tb_merchant.status
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.is_delete
     *
     * @return the value of tb_merchant.is_delete
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.is_delete
     *
     * @param isDelete the value for tb_merchant.is_delete
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.utime
     *
     * @return the value of tb_merchant.utime
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.utime
     *
     * @param utime the value for tb_merchant.utime
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.ctime
     *
     * @return the value of tb_merchant.ctime
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.ctime
     *
     * @param ctime the value for tb_merchant.ctime
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant.v_url
     *
     * @return the value of tb_merchant.v_url
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public String getvUrl() {
        return vUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant.v_url
     *
     * @param vUrl the value for tb_merchant.v_url
     *
     * @mbggenerated Mon Oct 16 22:58:39 CST 2017
     */
    public void setvUrl(String vUrl) {
        this.vUrl = vUrl == null ? null : vUrl.trim();
    }
}