package com.zhsj.m.model;

public class MerchantExtendInfo extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.id
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.mch_code
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String mchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.boss_id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String bossIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.boss_sdate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String bossSdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.boss_edate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String bossEdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.boss_positive
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String bossPositive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.boss_back
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String bossBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.bl_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String blNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.bl_merchant_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String blMerchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.bl_sdate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String blSdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.bl_edate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String blEdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.bl_pic
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String blPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.other_pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String otherPic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.other_pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String otherPic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_boss
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer accountBoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer accountIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_id_positive
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String accountIdPositive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_id_back
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String accountIdBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.bank_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.bank_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.bank_branch
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String bankBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_identity_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer accountIdentityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.weixin_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Double weixinSettleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.zhifubao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Double zhifubaoSettleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.qqqianbao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Double qqqianbaoSettleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.jdqianbao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Double jdqianbaoSettleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.yinlian_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Double yinlianSettleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.settle_day
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer settleDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.settle_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer settleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String accountPic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.account_pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String accountPic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String pic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String pic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.pic3
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String pic3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.is_qwx
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer isQwx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.qwx_id
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private String qwxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.utime
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_extend.ctime
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    private Integer ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.id
     *
     * @return the value of tb_merchant_extend.id
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.id
     *
     * @param id the value for tb_merchant_extend.id
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.mch_code
     *
     * @return the value of tb_merchant_extend.mch_code
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getMchCode() {
        return mchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.mch_code
     *
     * @param mchCode the value for tb_merchant_extend.mch_code
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setMchCode(String mchCode) {
        this.mchCode = mchCode == null ? null : mchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.boss_id_no
     *
     * @return the value of tb_merchant_extend.boss_id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBossIdNo() {
        return bossIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.boss_id_no
     *
     * @param bossIdNo the value for tb_merchant_extend.boss_id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBossIdNo(String bossIdNo) {
        this.bossIdNo = bossIdNo == null ? null : bossIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.boss_sdate
     *
     * @return the value of tb_merchant_extend.boss_sdate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBossSdate() {
        return bossSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.boss_sdate
     *
     * @param bossSdate the value for tb_merchant_extend.boss_sdate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBossSdate(String bossSdate) {
        this.bossSdate = bossSdate == null ? null : bossSdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.boss_edate
     *
     * @return the value of tb_merchant_extend.boss_edate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBossEdate() {
        return bossEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.boss_edate
     *
     * @param bossEdate the value for tb_merchant_extend.boss_edate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBossEdate(String bossEdate) {
        this.bossEdate = bossEdate == null ? null : bossEdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.boss_positive
     *
     * @return the value of tb_merchant_extend.boss_positive
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBossPositive() {
        return bossPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.boss_positive
     *
     * @param bossPositive the value for tb_merchant_extend.boss_positive
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBossPositive(String bossPositive) {
        this.bossPositive = bossPositive == null ? null : bossPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.boss_back
     *
     * @return the value of tb_merchant_extend.boss_back
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBossBack() {
        return bossBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.boss_back
     *
     * @param bossBack the value for tb_merchant_extend.boss_back
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBossBack(String bossBack) {
        this.bossBack = bossBack == null ? null : bossBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.bl_no
     *
     * @return the value of tb_merchant_extend.bl_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBlNo() {
        return blNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.bl_no
     *
     * @param blNo the value for tb_merchant_extend.bl_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBlNo(String blNo) {
        this.blNo = blNo == null ? null : blNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.bl_merchant_name
     *
     * @return the value of tb_merchant_extend.bl_merchant_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBlMerchantName() {
        return blMerchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.bl_merchant_name
     *
     * @param blMerchantName the value for tb_merchant_extend.bl_merchant_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBlMerchantName(String blMerchantName) {
        this.blMerchantName = blMerchantName == null ? null : blMerchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.bl_sdate
     *
     * @return the value of tb_merchant_extend.bl_sdate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBlSdate() {
        return blSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.bl_sdate
     *
     * @param blSdate the value for tb_merchant_extend.bl_sdate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBlSdate(String blSdate) {
        this.blSdate = blSdate == null ? null : blSdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.bl_edate
     *
     * @return the value of tb_merchant_extend.bl_edate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBlEdate() {
        return blEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.bl_edate
     *
     * @param blEdate the value for tb_merchant_extend.bl_edate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBlEdate(String blEdate) {
        this.blEdate = blEdate == null ? null : blEdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.bl_pic
     *
     * @return the value of tb_merchant_extend.bl_pic
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBlPic() {
        return blPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.bl_pic
     *
     * @param blPic the value for tb_merchant_extend.bl_pic
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBlPic(String blPic) {
        this.blPic = blPic == null ? null : blPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.other_pic1
     *
     * @return the value of tb_merchant_extend.other_pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getOtherPic1() {
        return otherPic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.other_pic1
     *
     * @param otherPic1 the value for tb_merchant_extend.other_pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setOtherPic1(String otherPic1) {
        this.otherPic1 = otherPic1 == null ? null : otherPic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.other_pic2
     *
     * @return the value of tb_merchant_extend.other_pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getOtherPic2() {
        return otherPic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.other_pic2
     *
     * @param otherPic2 the value for tb_merchant_extend.other_pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setOtherPic2(String otherPic2) {
        this.otherPic2 = otherPic2 == null ? null : otherPic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_type
     *
     * @return the value of tb_merchant_extend.account_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_type
     *
     * @param accountType the value for tb_merchant_extend.account_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_boss
     *
     * @return the value of tb_merchant_extend.account_boss
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getAccountBoss() {
        return accountBoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_boss
     *
     * @param accountBoss the value for tb_merchant_extend.account_boss
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountBoss(Integer accountBoss) {
        this.accountBoss = accountBoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_id_no
     *
     * @return the value of tb_merchant_extend.account_id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getAccountIdNo() {
        return accountIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_id_no
     *
     * @param accountIdNo the value for tb_merchant_extend.account_id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountIdNo(Integer accountIdNo) {
        this.accountIdNo = accountIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_id_positive
     *
     * @return the value of tb_merchant_extend.account_id_positive
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getAccountIdPositive() {
        return accountIdPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_id_positive
     *
     * @param accountIdPositive the value for tb_merchant_extend.account_id_positive
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountIdPositive(String accountIdPositive) {
        this.accountIdPositive = accountIdPositive == null ? null : accountIdPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_id_back
     *
     * @return the value of tb_merchant_extend.account_id_back
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getAccountIdBack() {
        return accountIdBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_id_back
     *
     * @param accountIdBack the value for tb_merchant_extend.account_id_back
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountIdBack(String accountIdBack) {
        this.accountIdBack = accountIdBack == null ? null : accountIdBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.id_no
     *
     * @return the value of tb_merchant_extend.id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.id_no
     *
     * @param idNo the value for tb_merchant_extend.id_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.bank_name
     *
     * @return the value of tb_merchant_extend.bank_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.bank_name
     *
     * @param bankName the value for tb_merchant_extend.bank_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.bank_no
     *
     * @return the value of tb_merchant_extend.bank_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.bank_no
     *
     * @param bankNo the value for tb_merchant_extend.bank_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_name
     *
     * @return the value of tb_merchant_extend.account_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_name
     *
     * @param accountName the value for tb_merchant_extend.account_name
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_no
     *
     * @return the value of tb_merchant_extend.account_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_no
     *
     * @param accountNo the value for tb_merchant_extend.account_no
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.bank_branch
     *
     * @return the value of tb_merchant_extend.bank_branch
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.bank_branch
     *
     * @param bankBranch the value for tb_merchant_extend.bank_branch
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch == null ? null : bankBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_identity_type
     *
     * @return the value of tb_merchant_extend.account_identity_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getAccountIdentityType() {
        return accountIdentityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_identity_type
     *
     * @param accountIdentityType the value for tb_merchant_extend.account_identity_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountIdentityType(Integer accountIdentityType) {
        this.accountIdentityType = accountIdentityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.weixin_settle_rate
     *
     * @return the value of tb_merchant_extend.weixin_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Double getWeixinSettleRate() {
        return weixinSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.weixin_settle_rate
     *
     * @param weixinSettleRate the value for tb_merchant_extend.weixin_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setWeixinSettleRate(Double weixinSettleRate) {
        this.weixinSettleRate = weixinSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.zhifubao_settle_rate
     *
     * @return the value of tb_merchant_extend.zhifubao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Double getZhifubaoSettleRate() {
        return zhifubaoSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.zhifubao_settle_rate
     *
     * @param zhifubaoSettleRate the value for tb_merchant_extend.zhifubao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setZhifubaoSettleRate(Double zhifubaoSettleRate) {
        this.zhifubaoSettleRate = zhifubaoSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.qqqianbao_settle_rate
     *
     * @return the value of tb_merchant_extend.qqqianbao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Double getQqqianbaoSettleRate() {
        return qqqianbaoSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.qqqianbao_settle_rate
     *
     * @param qqqianbaoSettleRate the value for tb_merchant_extend.qqqianbao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setQqqianbaoSettleRate(Double qqqianbaoSettleRate) {
        this.qqqianbaoSettleRate = qqqianbaoSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.jdqianbao_settle_rate
     *
     * @return the value of tb_merchant_extend.jdqianbao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Double getJdqianbaoSettleRate() {
        return jdqianbaoSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.jdqianbao_settle_rate
     *
     * @param jdqianbaoSettleRate the value for tb_merchant_extend.jdqianbao_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setJdqianbaoSettleRate(Double jdqianbaoSettleRate) {
        this.jdqianbaoSettleRate = jdqianbaoSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.yinlian_settle_rate
     *
     * @return the value of tb_merchant_extend.yinlian_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Double getYinlianSettleRate() {
        return yinlianSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.yinlian_settle_rate
     *
     * @param yinlianSettleRate the value for tb_merchant_extend.yinlian_settle_rate
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setYinlianSettleRate(Double yinlianSettleRate) {
        this.yinlianSettleRate = yinlianSettleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.settle_day
     *
     * @return the value of tb_merchant_extend.settle_day
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getSettleDay() {
        return settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.settle_day
     *
     * @param settleDay the value for tb_merchant_extend.settle_day
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setSettleDay(Integer settleDay) {
        this.settleDay = settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.settle_type
     *
     * @return the value of tb_merchant_extend.settle_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getSettleType() {
        return settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.settle_type
     *
     * @param settleType the value for tb_merchant_extend.settle_type
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setSettleType(Integer settleType) {
        this.settleType = settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_pic1
     *
     * @return the value of tb_merchant_extend.account_pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getAccountPic1() {
        return accountPic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_pic1
     *
     * @param accountPic1 the value for tb_merchant_extend.account_pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountPic1(String accountPic1) {
        this.accountPic1 = accountPic1 == null ? null : accountPic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.account_pic2
     *
     * @return the value of tb_merchant_extend.account_pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getAccountPic2() {
        return accountPic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.account_pic2
     *
     * @param accountPic2 the value for tb_merchant_extend.account_pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setAccountPic2(String accountPic2) {
        this.accountPic2 = accountPic2 == null ? null : accountPic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.pic1
     *
     * @return the value of tb_merchant_extend.pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getPic1() {
        return pic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.pic1
     *
     * @param pic1 the value for tb_merchant_extend.pic1
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setPic1(String pic1) {
        this.pic1 = pic1 == null ? null : pic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.pic2
     *
     * @return the value of tb_merchant_extend.pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.pic2
     *
     * @param pic2 the value for tb_merchant_extend.pic2
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.pic3
     *
     * @return the value of tb_merchant_extend.pic3
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getPic3() {
        return pic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.pic3
     *
     * @param pic3 the value for tb_merchant_extend.pic3
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setPic3(String pic3) {
        this.pic3 = pic3 == null ? null : pic3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.is_qwx
     *
     * @return the value of tb_merchant_extend.is_qwx
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getIsQwx() {
        return isQwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.is_qwx
     *
     * @param isQwx the value for tb_merchant_extend.is_qwx
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setIsQwx(Integer isQwx) {
        this.isQwx = isQwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.qwx_id
     *
     * @return the value of tb_merchant_extend.qwx_id
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public String getQwxId() {
        return qwxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.qwx_id
     *
     * @param qwxId the value for tb_merchant_extend.qwx_id
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setQwxId(String qwxId) {
        this.qwxId = qwxId == null ? null : qwxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.utime
     *
     * @return the value of tb_merchant_extend.utime
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.utime
     *
     * @param utime the value for tb_merchant_extend.utime
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setUtime(Integer utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_extend.ctime
     *
     * @return the value of tb_merchant_extend.ctime
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_extend.ctime
     *
     * @param ctime the value for tb_merchant_extend.ctime
     *
     * @mbggenerated Thu Oct 26 21:05:43 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }
}