package com.zhsj.m.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantFundAccount extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_fund_account.id
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_fund_account.merchant_id
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_fund_account.withdraw_amount
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    private BigDecimal withdrawAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_fund_account.freeze_amount
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    private BigDecimal freezeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_fund_account.password
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_fund_account.create_time
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchant_fund_account.update_time
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_fund_account.id
     *
     * @return the value of tb_merchant_fund_account.id
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_fund_account.id
     *
     * @param id the value for tb_merchant_fund_account.id
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_fund_account.merchant_id
     *
     * @return the value of tb_merchant_fund_account.merchant_id
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_fund_account.merchant_id
     *
     * @param merchantId the value for tb_merchant_fund_account.merchant_id
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_fund_account.withdraw_amount
     *
     * @return the value of tb_merchant_fund_account.withdraw_amount
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public BigDecimal getWithdrawAmount() {
        return withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_fund_account.withdraw_amount
     *
     * @param withdrawAmount the value for tb_merchant_fund_account.withdraw_amount
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public void setWithdrawAmount(BigDecimal withdrawAmount) {
        this.withdrawAmount = withdrawAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_fund_account.freeze_amount
     *
     * @return the value of tb_merchant_fund_account.freeze_amount
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public BigDecimal getFreezeAmount() {
        return freezeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_fund_account.freeze_amount
     *
     * @param freezeAmount the value for tb_merchant_fund_account.freeze_amount
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public void setFreezeAmount(BigDecimal freezeAmount) {
        this.freezeAmount = freezeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_fund_account.password
     *
     * @return the value of tb_merchant_fund_account.password
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_fund_account.password
     *
     * @param password the value for tb_merchant_fund_account.password
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_fund_account.create_time
     *
     * @return the value of tb_merchant_fund_account.create_time
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_fund_account.create_time
     *
     * @param createTime the value for tb_merchant_fund_account.create_time
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchant_fund_account.update_time
     *
     * @return the value of tb_merchant_fund_account.update_time
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchant_fund_account.update_time
     *
     * @param updateTime the value for tb_merchant_fund_account.update_time
     *
     * @mbggenerated Tue Oct 31 18:01:24 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}