package com.zhsj.m.model;

public class RoleBindRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_role.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_role.role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_role.assigned_role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer assignedRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_role.status
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_role.ctime
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_role.id
     *
     * @return the value of tb_role_bind_role.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_role.id
     *
     * @param id the value for tb_role_bind_role.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_role.role_id
     *
     * @return the value of tb_role_bind_role.role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_role.role_id
     *
     * @param roleId the value for tb_role_bind_role.role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_role.assigned_role_id
     *
     * @return the value of tb_role_bind_role.assigned_role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getAssignedRoleId() {
        return assignedRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_role.assigned_role_id
     *
     * @param assignedRoleId the value for tb_role_bind_role.assigned_role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setAssignedRoleId(Integer assignedRoleId) {
        this.assignedRoleId = assignedRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_role.status
     *
     * @return the value of tb_role_bind_role.status
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_role.status
     *
     * @param status the value for tb_role_bind_role.status
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_role.ctime
     *
     * @return the value of tb_role_bind_role.ctime
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_role.ctime
     *
     * @param ctime the value for tb_role_bind_role.ctime
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }
}