package com.zhsj.m.model;

import java.util.Date;

public class RoleBindChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_channel.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_channel.role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_channel.channel_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_channel.status
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_channel.create_time
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_channel.update_time
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_bind_channel.is_delete
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_channel.id
     *
     * @return the value of tb_role_bind_channel.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_channel.id
     *
     * @param id the value for tb_role_bind_channel.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_channel.role_id
     *
     * @return the value of tb_role_bind_channel.role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_channel.role_id
     *
     * @param roleId the value for tb_role_bind_channel.role_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_channel.channel_id
     *
     * @return the value of tb_role_bind_channel.channel_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_channel.channel_id
     *
     * @param channelId the value for tb_role_bind_channel.channel_id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_channel.status
     *
     * @return the value of tb_role_bind_channel.status
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_channel.status
     *
     * @param status the value for tb_role_bind_channel.status
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_channel.create_time
     *
     * @return the value of tb_role_bind_channel.create_time
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_channel.create_time
     *
     * @param createTime the value for tb_role_bind_channel.create_time
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_channel.update_time
     *
     * @return the value of tb_role_bind_channel.update_time
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_channel.update_time
     *
     * @param updateTime the value for tb_role_bind_channel.update_time
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_bind_channel.is_delete
     *
     * @return the value of tb_role_bind_channel.is_delete
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_bind_channel.is_delete
     *
     * @param isDelete the value for tb_role_bind_channel.is_delete
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}