package com.zhsj.m.model;

public class SystemInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_system.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_system.system_name
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private String systemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_system.ctime
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    private Integer ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_system.id
     *
     * @return the value of td_system.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_system.id
     *
     * @param id the value for td_system.id
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_system.system_name
     *
     * @return the value of td_system.system_name
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_system.system_name
     *
     * @param systemName the value for td_system.system_name
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_system.ctime
     *
     * @return the value of td_system.ctime
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_system.ctime
     *
     * @param ctime the value for td_system.ctime
     *
     * @mbggenerated Sun Oct 15 16:02:14 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }
}