$(function(){
	$(".wordd").click(function(){
		if($(this).find("p").text()=="高级搜索"){
			$(this).find("p").text("收起高级搜索");
			$(this).find("img").hide();
			$(".name_two").show();
			$(".name_three").show();
		}else{
			$(this).find("p").text("高级搜索");
			$(this).find("img").show();
			$(".name_two").hide();
			$(".name_three").hide();
		}			
	})
	$(".word_right").click(function(){
		if($(this).find("p").text()=="查看更多数据"){
			$(this).find("p").text("收起更多数据");
			$(this).find("img").hide();
			$(".data").show();
		}else{
			$(this).find("p").text("查看更多数据");
			$(this).find("img").show();
			$(".data").hide();
		}	
	})
	$(".all").click(function(){
		$(this).find("div").toggle();
	})
	$(".none>p").click(function(){
		$(".all>p").html($(this).html());
	})
	$(".pay").click(function(){
		$(this).find("div").toggle();
	})
	$(".none1>p").click(function(){
		$(".pay>p").html($(this).html());
	})
	$(".state").click(function(){
		$(this).find("div").toggle();
	})
	$(".none2>p").click(function(){
		$(".state>p").html($(this).html());
	})
	$(".time>span").click(function(){
		$(this).addClass("hover").siblings().removeClass("hover");
	})
	$(".account_manage>ul>li").click(function(){
		$(this).addClass("active").siblings().removeClass("active");
		$(".content>ol>li").eq($(this).index()).show().siblings().hide();
	})
	$(".account_manage>ul>li.two").click(function(){
		$(".inquier>div.time>div").clone(true).appendTo($(".rec>div.time"));
		$(".inquier>div.time>div").remove();
	})
	$(".account_manage>ul>li.on").click(function(){
		$(".rec>div.time>div").clone(true).appendTo($(".inquier>div.time"));
		$(".rec>div.time>div").remove();
	})
	$(".inp_1").click(function(){
		$(this).find("div").toggle();
	})
	$(".inp_3").click(function(){
		$(this).find("div").toggle();
	})
	$(".inp_4").click(function(){
		$(this).find("div").toggle();
	})
})